# Generated by Django 3.1 on 2020-09-09 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardOfDirector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350)),
                ('position', models.CharField(max_length=350)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=340)),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=234)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Galery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=234, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350)),
                ('position', models.CharField(max_length=350)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Portifolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=234)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=234)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('content', models.TextField()),
                ('published_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Principle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=234)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectObjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=340)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=340)),
            ],
        ),
        migrations.CreateModel(
            name='TargetedBeneficiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=340)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=340)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wards', to='pages.district')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=340)),
                ('status', models.CharField(choices=[('ongoing', 'ONGOING'), ('finished', 'FINISHED'), ('not', 'NOT COMMERNCED'), ('suspended', 'SUSPENDED')], max_length=340)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('duration', models.CharField(choices=[('1 month', 'ONE MONTH'), ('2 months', 'TWO MONTHS'), ('3 months', 'THREE MONTHS'), ('4 months', 'FOUR MONTHS'), ('5 months', 'FIVE MONTHS'), ('6 months', 'SIX MONTHS'), ('7 months', 'SEVEN MONTHS'), ('8 months', 'EIGHT MONTHS'), ('9 months', 'NINE MONTHS'), ('10 months', 'TEN MONTHS'), ('11 months', 'ELEVEN MONTHS'), ('12 months', 'TWELVE MONTHS'), ('13 months', 'THIRTEEN MONTHS'), ('14 months', 'FOUTEEN MONTHS'), ('15 months', 'FIFTEEN MONTHS'), ('16 months', 'SIXTEEN MONTHS'), ('17 months', 'SEVENTEEN MONTHS'), ('18 months', 'EIGHTEEN MONTHS'), ('19 months', 'NINTEEN MONTHS'), ('20 months', 'TWENTY MONTHS'), ('21 months', 'TWENTY-ONE MONTHS'), ('22 months', 'TWENTY-TWO MONTHS'), ('23 months', 'TWENTY-THREE MONTHS'), ('24 months', 'TWENTY-FOUE MONTHS'), ('25 months', 'TWENTY-FIVE MONTHS'), ('26 months', 'TWENTY-SIX MONTHS'), ('27 months', 'TWENTY-SEVEN MONTHS'), ('28 months', 'TWENTY-EIGHT MONTHS'), ('29 months', 'TWENTY-NINE MONTHS'), ('30 months', 'THIRTY MONTHS'), ('31 months', 'THIRTY-ONE MONTHS'), ('32 months', 'THIRTY-TWO MONTHS'), ('33 months', 'THIRTY-THREE MONTHS'), ('34 months', 'THIRTY-FOUE MONTHS'), ('35 months', 'THIRTY-FIVE MONTHS'), ('36 months', 'THIRTY-SIX MONTHS')], max_length=100)),
                ('beneficiary_population', models.IntegerField()),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('image_6', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('image_7', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('image_8', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('image_9', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('image_10', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('beneficiaries', models.ManyToManyField(to='pages.TargetedBeneficiary')),
                ('objectives', models.ManyToManyField(to='pages.ProjectObjective')),
                ('partners', models.ManyToManyField(to='pages.Partner')),
                ('portifolios', models.ManyToManyField(to='pages.Portifolio')),
                ('project_areas', models.ManyToManyField(to='pages.Ward')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('galery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='pages.galery')),
            ],
        ),
        migrations.AddField(
            model_name='galery',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery', to='pages.project'),
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='districts', to='pages.province'),
        ),
    ]
